<header>
    <div class="header">
        <h1><a href="<?php echo $this->baseUrl ?>/admin/"><?php echo $this->layout()->titulo ?> <span>&#8629</span> <em>Admin</em></a></h1>
        <div class="menu clearfix">
            <div class="left">
                <a href="<?php echo $this->baseUrl ?>/">Frontend</a> 
                &nbsp;&nbsp;<span>|</span>&nbsp;&nbsp;
                <a href="<?php echo $this->baseUrl ?>/admin/">Inicio</a>                             
            </div>
            <div class="right">                
                <?php echo $this->AdminLogin() ?>
            </div>
        </div>
    </div>    
</header>    