<h3><?php echo $this->titulo ?></h3>

<section id="busquedaUsuarios">
    
    <div class="busquedaUsuarios_wrapper clearfix">

        <?php if ($this->linkVolver) : ?>

            <div class="left">
                <ul class="actionList clearfix">
                    <li><a href="<?php echo $this->baseUrl ?>/usuarios/"><span>Volver al listado</span></a></li>
                </ul>
            </div>

        <?php endif; ?>

        <div class="right">

            <?php //if (isset($this->errors['nombre'])) : ?>

            <!--<div  class="form-errors">
                     <?php //foreach ($this->errors['nombre'] as $e) :?>
                        <?php //echo $e ?>
                     <?php //endforeach ?>
                </div>-->

            <?php //endif ?>

            <div id="form-errors">
                Ingrese un valor para la búsqueda 
            </div>

            <?php echo $this->form ?>

        </div>

    </div>    
    
</section>

<hr />

<?php if(count($this->listaUsuario) > 0): ?>

    <table class="list">

        <thead>
            <tr>
                <th>Usuario</th>
                <?php if ( $this->verEmails ) : ?>
                    <th>Email</th>
                <?php endif; ?>
                <th>Creado</th>
                <th>Nombre</th>
                <th>Apellido</th>
                <th>Sitio web</th>                
                <th>Comentarios en Productos</th>
                <th>Acciones</th>
            </tr>
        </thead>

        <tbody>
            <?php foreach($this->listaUsuario as $usuario): ?>

                <tr>
                    <td>
                        <img src="<?php echo $this->baseUrl ?>/<?php echo $this->thumbPath . $usuario->getFoto() ?>" alt="<?php echo $usuario->getUsuario() ?>" />
                        <?php echo $usuario->getUsuario() ?>
                    </td>
                    <?php if ( $this->verEmails ) : ?>                    
                        <td><?php echo $usuario->getEmail() ?></td>
                    <?php endif; ?>
                    <td><small><?php echo $usuario->getFecha_cre() ?></small></td>
                    <td><?php echo $usuario->getNombre() ?></td>
                    <td><?php echo $usuario->getApellido() ?></td>
                    <td><small><?php echo $usuario->getWebsite() ?></small></td>                    
                    <td class="productComments">
                        <?php if(count($usuario->getComentarios()) > 0): ?>
                            <ol>
                            <?php foreach ($usuario->getComentarios() as $comentario): ?>
                               <li><?php echo $comentario->getComentario() ?></li>
                            <?php endforeach; ?>
                            </ol>
                        <?php else: ?>
                            <small>no comments</small>
                        <?php endif;?>

                    </td>                         
                    <td class="action"><a href="<?php echo $this->baseUrl ?>/usuarios/index/ver/id/<?php echo $usuario->getId() ?>/"><span>ver</span></a></td>
                </tr>

            <?php endforeach; ?>
        </tbody>        

    </table>

<?php else: ?>

    <p>Usuarios <strong>no</strong> encontrados en el sistema.</p>
    
<?php endif;?>