<h3><?php echo $this->titulo ?></h3>

<hr />

<p>El proyecto cumple el estándar PHP Zend Company: comprendiendo la arquitectura del modelo MVC, haciendo uso de los diversos componentes y APIs para el manejo de formularios con Zend_Form, validaciones de datos, abstraer las conexiones y operaciones a la base de datos utilizando Doctrine 2 y ORM, autenticación de usuarios con Zend_Auth y Zend_Acl, email con Zend_Mail, logs Zend_Log, Sistemas de Layout con Zend_Layout, AJAX con ZendX_JQuery, la nueva funcionalidad de RAD (Rapid Application Development) a través de comandos de consola con Zend Tool, etc..</p>

<hr />  
  
<ul class="actionList clearfix">
    <li><a href="<?php echo $this->baseUrl() ?>/index/demo-jquery-ui/"><span>demo jQuery UI</span></a></li>
    <li><a href="<?php echo $this->baseUrl() ?>/index/hola/"><span>hola</span></a></li>
    <!-- <li><a href="<?php //echo $this->baseUrl() ?>/index/fool/"><span>fool</span></a></li> -->
</ul>