<!-- 

<?php //if ($this->denyModule == "admin" ) : ?>

<p>Admin</p>

<?php //else: ?>

<h3><strong><?php //echo $this->denyAction ?></strong> es una página privada</h3>
<p>Por favor <a href="<?php //echo $this->baseUrl ?>/usuarios/login/" style="text-decoration:underline">inicia sesión</a> para ingresar.</p>

<?php //endif ?>

-->

<h3><strong><?php echo $this->denyAction ?></strong> es una página privada</h3>
<p>Por favor <a href="<?php echo $this->baseUrl ?>/usuarios/login/" style="text-decoration:underline">inicia sesión</a> para ingresar.</p>
