<h3>Error</h3>

<p><strong><?php echo $this->message ?></strong></p>

<?php if (isset($this->exception)): ?>

<!--<h3>Exception information:</h3>-->
  <p>
      <b>Mensaje:</b> <?php echo $this->exception->getMessage() ?>
  </p>

<!--
  <h3>Stack trace:</h3>
  <pre style="overflow: hidden"><?php //echo $this->exception->getTraceAsString() ?></pre>

  <h3>Request Parameters:</h3>
  <pre style="overflow: hidden"><?php //echo $this->escape(var_export($this->request->getParams(), true)) ?></pre>
-->

<?php endif ?>
