<h3><?php echo $this->titulo; ?></h3>

<section id="busquedaProductos">
    
    <div class="busquedaProductos_wrapper clearfix">

        <?php if ($this->linkVolver) : ?>

            <div class="left">
                <ul class="actionList clearfix">
                    <li><a href="<?php echo $this->baseUrl ?>/catalogo/"><span>Volver al listado</span></a></li>
                </ul>
            </div>

        <?php endif; ?>

        <div class="right">

            <div id="form-errors">
                Ingrese un valor para la búsqueda 
            </div>

            <?php echo $this->form ?>

        </div>

    </div>    
    
</section>

<hr />

<?php if(count($this->listaProducto) > 0): ?>
    <table class="list">
        <tr>
            <th>Descripción</th>
            <?php if ( $this->verPrecios ) : ?>
                <th>Precio</th>
            <?php endif; ?>
            <th>Cantidad</th>
            <th>Comentarios</th> 
            <th>Acciones</th>
        </tr>
        <?php foreach($this->listaProducto as $producto): ?>
        <tr>
            <td><?php echo $producto->getDescripcion() ?></td>
            <?php if ( $this->verPrecios ) : ?>
                <td><?php echo $producto->getPrecio() ?></td>
            <?php endif; ?>
            <td><?php echo $producto->getCantidad() ?></td>
            <td class="productComments">
                <?php if(count($producto->getComentarios()) > 0): ?>
                    <ol>
                    <?php foreach ($producto->getComentarios() as $comentario): ?>
                       <li><?php echo $comentario->getComentario() ?></li>
                    <?php endforeach; ?>
                    </ol>
                <?php else: ?>
                    <small>no comments</small>
                <?php endif;?>

            </td>            
            <td class="action"><a href="<?php echo $this->baseUrl ?>/catalogo/index/ver/id/<?php echo $producto->getId() ?>/"><span>ver</span></a></td>           
        </tr>
        <?php endforeach; ?>
    </table>
<?php else: ?>
	<p>Productos <strong>no</strong> encontrados en el sistema.</p>
<?php endif;?>

        
<script type="text/javascript">
    <!--
        document.forms["busqueda-productos"].onsubmit = function(){
            if ( this.elements["descripcion"].value.length < 2 ) {
                document.getElementById("form-errors").style.display = "block";
                return false;
            }
        }
    -->
</script>        